/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mh.gui;

import com.mh.biz.MaquinaHelados;
import com.mh.biz.pojo.Helado;
import com.mh.exceptions.NotEnoughMoneyException;
import com.mh.exceptions.NotValidPositionException;
import com.mh.exceptions.QuantityExceededException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ExecGUI extends javax.swing.JFrame {

    /**
     * Creates new form ExecGUI
     */
    public ExecGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHelados = new javax.swing.JTable();
        jButtonSaldo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelSaldoHeader = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPosicionHeader = new javax.swing.JLabel();
        jLabelPosicion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonVueltas = new javax.swing.JButton();
        jButtonSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jTableHelados.setBackground(new java.awt.Color(40, 100, 40));
        jTableHelados.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTableHelados.setForeground(new java.awt.Color(40, 200, 40));
        jTableHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Nombre", "Precio", "Tipo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHelados.setToolTipText("");
        jTableHelados.setGridColor(new java.awt.Color(40, 150, 40));
        jTableHelados.setSelectionBackground(new java.awt.Color(40, 150, 40));
        jTableHelados.setSelectionForeground(new java.awt.Color(70, 255, 70));
        jTableHelados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableHelados.setShowGrid(false);
        jTableHelados.getTableHeader().setReorderingAllowed(false);
        jTableHelados.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableHeladosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTableHelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableHeladosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHelados);

        jButtonSaldo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSaldo.setText("Añadir");
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(40, 100, 40));
        jPanel1.setForeground(new java.awt.Color(40, 200, 40));

        jLabelSaldo.setBackground(new java.awt.Color(40, 100, 40));
        jLabelSaldo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(40, 200, 40));
        jLabelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaldo.setText("0,00 €");

        jLabelSaldoHeader.setBackground(new java.awt.Color(40, 100, 40));
        jLabelSaldoHeader.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabelSaldoHeader.setForeground(new java.awt.Color(40, 200, 40));
        jLabelSaldoHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaldoHeader.setText("Saldo");

        jPanel4.setBackground(new java.awt.Color(40, 200, 40));
        jPanel4.setForeground(new java.awt.Color(40, 200, 40));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSaldoHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaldoHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(40, 100, 40));
        jPanel2.setForeground(new java.awt.Color(40, 200, 40));

        jLabelPosicionHeader.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabelPosicionHeader.setForeground(new java.awt.Color(40, 200, 40));
        jLabelPosicionHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosicionHeader.setText("Posición");

        jLabelPosicion.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelPosicion.setForeground(new java.awt.Color(40, 200, 40));
        jLabelPosicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosicion.setText("- -");

        jPanel3.setBackground(new java.awt.Color(40, 200, 40));
        jPanel3.setForeground(new java.awt.Color(40, 200, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPosicionHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPosicionHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton0.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonVueltas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonVueltas.setText("Vueltas");
        jButtonVueltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVueltasActionPerformed(evt);
            }
        });

        jButtonSelect.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonSelect.setText("Seleccionar");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVueltas))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVueltas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cargamos los datos al iniciar
    private void jTableHeladosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableHeladosAncestorAdded
        // TODO add your handling code here:

        //Centra el los elementos de la tabla
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.LEFT);
        this.jTableHelados.setDefaultRenderer(Object.class, centerRenderer);

        //Leemos los datos
        DefaultTableModel dtm = (DefaultTableModel) this.jTableHelados.getModel();
        List<Helado> helados = null;
        
        try {
            helados = mh.cargarHelados();
        } catch (Exception ex) {
            System.out.println("Se ha producido un error inesperado. Por favor, contacte con el administrador.");
        }

        //Aplicamos en la tabla
        for (Helado helado : helados) {
            Object[] o = {helado.getPosicion(), helado.getNombre(), helado.getPrecio(), helado.getTipo(), helado.getCantidad()};
            dtm.addRow(o);
        }
    }//GEN-LAST:event_jTableHeladosAncestorAdded

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        if (this.jLabelPosicion.getText().length() >= 2) {
            this.jLabelPosicion.setText("0");
        } else {
            this.jLabelPosicion.setText(this.jLabelPosicion.getText() + "0");
        }

    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.jLabelPosicion.getText().length() >= 2) {
            this.jLabelPosicion.setText("1");
        } else {
            this.jLabelPosicion.setText(this.jLabelPosicion.getText() + "1");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (this.jLabelPosicion.getText().length() >= 2) {
            this.jLabelPosicion.setText("2");
        } else {
            this.jLabelPosicion.setText(this.jLabelPosicion.getText() + "2");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:

        this.jLabelPosicion.setText("- -");

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTableHeladosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHeladosMouseReleased
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) this.jTableHelados.getModel();
        int r = this.jTableHelados.getSelectedRow();
        this.jLabelPosicion.setText(dtm.getValueAt(r, 0) + "");

    }//GEN-LAST:event_jTableHeladosMouseReleased

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
        // TODO add your handling code here:
        MonedasJDialog md = new MonedasJDialog(this, true);
        md.setVisible(true);

        //Actualizamos en UI
        JPanel p = (JPanel) md.getContentPane().getComponent(0);
        JLabel l = (JLabel) p.getComponent(0);
        String[] dinero = l.getText().split(" ");
        
        mh.setMonedero(Double.parseDouble(dinero[0]) + mh.getMonedero());
        this.jLabelSaldo.setText(String.valueOf(mh.getMonedero()));
        

    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void jButtonVueltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVueltasActionPerformed
        // TODO add your handling code here:
        VueltasJDialog vd = new VueltasJDialog(this, true);
        
        JPanel p = (JPanel) vd.getContentPane().getComponent(0);
        JLabel l = (JLabel) p.getComponent(0);

        //Actualizamos en UI
        String[] saldo = l.getText().split(":");
        l.setText(saldo[0] + " : " + String.valueOf(mh.getMonedero()));
        
        vd.setVisible(true);
        
        this.jLabelSaldo.setText("0,00 €");

        //Actualizamos en maquina de helados
        mh.setMonedero(0);
    }//GEN-LAST:event_jButtonVueltasActionPerformed

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
        // TODO add your handling code here:

        VueltasJDialog vd = new VueltasJDialog(this, true);
        String posicion = this.jLabelPosicion.getText();
        Helado conseguido = null;
        
        try {
            
            conseguido = mh.pedirHelado(posicion);
            if (conseguido != null) {
                JPanel p = (JPanel) vd.getContentPane().getComponent(0);
                JLabel l = (JLabel) p.getComponent(0);
                l.setText("Sus vueltas: " + String.valueOf(mh.getMonedero()) + " €");
                
                mh.setMonedero(0);
                this.jLabelSaldo.setText("0,00 €");
                
            }
            
            vd.setVisible(true);
            
        } catch (NotValidPositionException e) {
            System.out.println("Posición introducida inexistente");
        } catch (QuantityExceededException e) {
            System.out.println("No quedan helados en esa posición");
        } catch (NotEnoughMoneyException e) {
            System.out.println("No tiene dinero suficiente para ese helado");
        } catch (Exception e) {
            System.out.println("Se ha producido un error inesperado. Por favor, contacte con el administrador.");
        }

    }//GEN-LAST:event_jButtonSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecGUI().setVisible(true);
            }
        });
        
    }
    
    private MaquinaHelados mh = new MaquinaHelados();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JButton jButtonVueltas;
    private javax.swing.JLabel jLabelPosicion;
    private javax.swing.JLabel jLabelPosicionHeader;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelSaldoHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHelados;
    // End of variables declaration//GEN-END:variables
}
